spring:
  config:
    import: optional:myInfo.yml
  datasource:
    url: jdbc:mysql://${db.url}:${db.port}/${db.name}
    username: ${db.user}
    password: ${db.pw}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
#    show-sql: false
    show-sql: true
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  data:
    redis:
      port: 6379
      host: localhost

  security:
    config:
      import: optional:myInfo.yml
    user:
      name: ${secure.admin}
      password: ${secure.password}

jwt:
  config:
    import: optional:myInfo.yml
  secretKey: ${secure.key}
  tokenTime: ${secure.timer}

cloud:
  config:
    import: optional:myInfo.yml
  aws:
    credentials:
      access-key: ${s3.aKey}
      secret-key: ${s3.sKey}

api:
  spam-check:
    url: "https://apick.app/rest/check_spam_number"
    auth-key: f4856687c81a60da1932589803df35fd

logging:
  level:
    root: info
    com.example.codePicasso: info
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/application-%d{yyyy-MM-dd}.log
      max-history: 365
      max-file-size: 100MB